name: Weathercaster JMA

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      WEATHERCASTER_USER: ${{ secrets.WEATHERCASTER_USER }}
      WEATHERCASTER_PASS: ${{ secrets.WEATHERCASTER_PASS }}
      WEATHERCASTER_DRIVE_FOLDER_ID: ${{ secrets.WEATHERCASTER_DRIVE_FOLDER_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: sudo apt-get update && sudo apt-get install -y poppler-utils
      - run: python daily_weathercaster_notify.py
