# .github/workflows/test.yml
# ===============================================
# MSM GPVファイルを描画 → Slackへ自動投稿テスト
# ===============================================

name: Test

on:
  workflow_dispatch:

run: echo "START"
